CREATE DATABASE db_task;

CREATE TABLE store(
店舗ID INT PRIMARY KEY,
店舗名 VARCHAR(50) NOT NULL,
住所 VARCHAR(50) NOT NULL,
電話番号 VARCHAR(20) NOT NULL);

CREATE TABLE goods(
商品ID INT PRIMARY KEY,
商品名 VARCHAR(50) NOT NULL,
単価 INT NOT NULL,
値引率 INT);

CREATE TABLE pay_method(
ID INT PRIMARY KEY,
支払方法 VARCHAR(50) NOT NULL);
/*
CREATE TABLE employee(
店舗ID INT REFERENCES store(店舗ID),
責任者ID VARCHAR(50) UNIQUE,
氏名 VARCHAR(50) NOT NULL,
PRIMARY KEY(店舗ID, 責任者ID));
*/
CREATE TABLE receipt(
伝票番号 INT PRIMARY KEY,
店舗ID INT NOT NULL REFERENCES store(店舗ID),
日付 DATE NOT NULL,
時間 TIME NOT NULL,
レジ番号 INT NOT NULL,
責任者ID VARCHAR(50) NOT NULL);

CREATE TABLE sales(
ID INT PRIMARY KEY,
伝票番号 INT NOT NULL REFERENCES receipt(伝票番号),
商品ID INT NOT NULL REFERENCES goods(商品ID),
個数 INT NOT NULL,
消費税率 INT NOT NULL);

CREATE TABLE pay(
ID INT PRIMARY KEY,
伝票番号 INT NOT NULL REFERENCES receipt(伝票番号),
支払方法１ INT NOT NULL REFERENCES pay_method(ID),
支払方法２ INT REFERENCES pay_method(ID),
受領額 INT,
お釣り INT,
使用ポイント INT);

DROP TABLE pay;
DROP TABLE sales;
DROP TABLE receipt;
DROP TABLE employee;
